AllCops:
  Exclude:
    - "app/assets/**/*"
    - "app/views/**/*"
    - "bin/**/*"
    - "bundle_bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - "Gemfile.lock"
